### ISSUE TITLE
السلام عليكم 

### ISSUE THREAD

**Issue by luckyMansour** [Moka-admin0/Np-4.0_MiniGames#2]
كيف طريقة الاستعمال داخل فايف ام انا ما اقصد الكوماند انا اقصد كيف اربطة بسرقة او شي من هذا القبيل ؟

**Comment by Moka-admin0** [comment]
العذر و السموحة توني اشوف, اتوقع بعد هاذا الوقت انت عرفت كيف تحلها واذا ما عرفت سوي اكسبورت و الله يوفقك
